services:
  database:
    image: postgres:15
    restart: "no"
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: $PWD/initdb.sql
        target: /docker-entrypoint-initdb.d/initdb.sql
        read_only: true
  pgadmin:
    image: dpage/pgadmin4:6
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@database.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_DISABLE_POSTFIX: "true"
    volumes:
      - type: bind
        source: $PWD/servers.json
        target: /pgadmin4/servers.json
        read_only: true
